// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.924
package views

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Dashboard() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div id=\"dashboard\"><article><header><b>🗓️ Aktualizacja danych</b></header>Prosimy Cię o krótką aktualizację informacji o Twojej organizacji — to pomoże nam lepiej i szybciej nieść pomoc.<hr><details name=\"charity_update\"><summary class=\"outline\" role=\"button\">🗹 Dane adresowe</summary><p>Test testowy</p></details> <details name=\"charity_update\"><summary class=\"outline\" role=\"button\">□ Kontakty</summary><ul><li>...</li><li>...</li></ul></details> <details name=\"charity_update\"><summary class=\"outline\" role=\"button\">□ Beneficjenci</summary><p>...</p></details> <details name=\"charity_update\"><summary class=\"outline\" role=\"button\">□ Źródła żywności</summary><p>...</p></details> <details name=\"charity_update\"><summary class=\"outline\" role=\"button\">□ Warunki udzielania pomocy żywnościowej</summary><p>...</p></details></article></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
