// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

type Organizacje struct {
	Teczka                              int64
	Identyfikatorenova                  string
	Nip                                 string
	Regon                               string
	Krsnr                               string
	Formaprawna                         string
	Opp                                 bool
	Nazwaorganizacjipodpisujacejumowe   string
	Adresrejestrowy                     string
	Nazwaplacowkitrafiazywnosc          string
	Adresplacowkitrafiazywnosc          string
	Gminadzielnica                      string
	Powiat                              string
	Nazwaorganizacjiksiegowaniedarowizn string
	Ksiegowanieadres                    string
	Telorganprowadzacegoksiegowosc      string
	Wwwfacebook                         string
	Telefon                             string
	Przedstawiciel                      string
	Kontakt                             string
	Email                               string
	Dostepnosc                          string
	Osobadokontaktu                     string
	Telefonosobykontaktowej             string
	Mailosobykontaktowej                string
	Osobaodbierajacazywnosc             string
	Telefonosobyodbierajacej            string
	Liczbabeneficjentow                 int32
	Beneficjenci                        string
	Sieci                               bool
	Bazarki                             bool
	Machfit                             bool
	Fepz2024                            bool
	Odbiorkrotkitermin                  bool
	Tylkonaszmagazyn                    bool
	Kategoria                           string
	Rodzajpomocy                        string
	Sposobudzielaniapomocy              string
	Warunkimagazynowe                   string
	Haccp                               bool
	Sanepid                             bool
	Transportopis                       string
	Transportkategoria                  string
}
