// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package database

import (
	"context"
)

const readCharity = `-- name: ReadCharity :one
SELECT
    Teczka,
    IdentyfikatorEnova,
    NIP,
    Regon,
    KrsNr,
    FormaPrawna,
    OPP,
    NazwaOrganizacjiPodpisujacejUmowe,
    AdresRejestrowy,
    NazwaPlacowkiTrafiaZywnosc,
    AdresPlacowkiTrafiaZywnosc,
    GminaDzielnica,
    Powiat,
    NazwaOrganizacjiKsiegowanieDarowizn,
    KsiegowanieAdres,
    TelOrganProwadzacegoKsiegowosc,
    WwwFacebook,
    Telefon,
    Przedstawiciel,
    Kontakt,
    Email,
    Dostepnosc,
    OsobaDoKontaktu,
    TelefonOsobyKontaktowej,
    MailOsobyKontaktowej,
    OsobaOdbierajacaZywnosc,
    TelefonOsobyOdbierajacej,
    LiczbaBeneficjentow,
    Beneficjenci,
    Sieci,
    Bazarki,
    Machfit,
    FEPZ2024,
    OdbiorKrotkiTermin,
    TylkoNaszMagazyn,
    Kategoria,
    RodzajPomocy,
    SposobUdzielaniaPomocy,
    WarunkiMagazynowe,
    HACCP,
    Sanepid,
    TransportOpis,
    TransportKategoria
FROM organizacje
WHERE email = $1 LIMIT 1
`

func (q *Queries) ReadCharity(ctx context.Context, email string) (Organizacje, error) {
	row := q.db.QueryRow(ctx, readCharity, email)
	var i Organizacje
	err := row.Scan(
		&i.Teczka,
		&i.Identyfikatorenova,
		&i.Nip,
		&i.Regon,
		&i.Krsnr,
		&i.Formaprawna,
		&i.Opp,
		&i.Nazwaorganizacjipodpisujacejumowe,
		&i.Adresrejestrowy,
		&i.Nazwaplacowkitrafiazywnosc,
		&i.Adresplacowkitrafiazywnosc,
		&i.Gminadzielnica,
		&i.Powiat,
		&i.Nazwaorganizacjiksiegowaniedarowizn,
		&i.Ksiegowanieadres,
		&i.Telorganprowadzacegoksiegowosc,
		&i.Wwwfacebook,
		&i.Telefon,
		&i.Przedstawiciel,
		&i.Kontakt,
		&i.Email,
		&i.Dostepnosc,
		&i.Osobadokontaktu,
		&i.Telefonosobykontaktowej,
		&i.Mailosobykontaktowej,
		&i.Osobaodbierajacazywnosc,
		&i.Telefonosobyodbierajacej,
		&i.Liczbabeneficjentow,
		&i.Beneficjenci,
		&i.Sieci,
		&i.Bazarki,
		&i.Machfit,
		&i.Fepz2024,
		&i.Odbiorkrotkitermin,
		&i.Tylkonaszmagazyn,
		&i.Kategoria,
		&i.Rodzajpomocy,
		&i.Sposobudzielaniapomocy,
		&i.Warunkimagazynowe,
		&i.Haccp,
		&i.Sanepid,
		&i.Transportopis,
		&i.Transportkategoria,
	)
	return i, err
}
