package database

import "context"

var ReadCharityByEmailMock ReadCharityByEmail = func(_ context.Context, _ string) (Organizacje, error) {
    return Organizacje{
        Teczka:                              1,
        Identyfikatorenova:                  "EN123456",
        Nip:                                 "1234567890",
        Regon:                               "987654321",
        Krsnr:                               "KRS123456",
        Formaprawna:                         "Fundacja",
        Opp:                                 true,
        Nazwaorganizacjipodpisujacejumowe:   "Fundacja Dobroczynna",
        Adresrejestrowy:                     "ul. Dobra 1, 00-001 Warszawa",
        Nazwaplacowkitrafiazywnosc:          "Placówka Główna",
        Adresplacowkitrafiazywnosc:          "ul. Pomocna 5, 00-002 Warszawa",
        Gminadzielnica:                      "Śródmieście",
        Powiat:                              "Warszawa",
        Nazwaorganizacjiksiegowaniedarowizn: "Fundacja Dobroczynna - Księgowość",
        Ksiegowanieadres:                    "ul. Księgowa 10, 00-003 Warszawa",
        Telorganprowadzacegoksiegowosc:      "+48 123 456 789",
        Wwwfacebook:                         "https://facebook.com/fundacjadobroczynna",
        Telefon:                             "+48 987 654 321",
        Przedstawiciel:                      "Jan Kowalski",
        Kontakt:                             "kontakt@fundacja.pl",
        Email:                               "info@fundacja.pl",
        Dostepnosc:                          "Poniedziałek–Piątek 9:00–17:00",
        Osobadokontaktu:                     "Anna Nowak",
        Telefonosobykontaktowej:             "+48 555 444 333",
        Mailosobykontaktowej:                "anna.nowak@fundacja.pl",
        Osobaodbierajacazywnosc:             "Piotr Zieliński",
        Telefonosobyodbierajacej:            "+48 222 333 444",
        Liczbabeneficjentow:                 150,
        Beneficjenci:                        "Rodziny wielodzietne, osoby starsze",
        Sieci:                               true,
        Bazarki:                             false,
        Machfit:                             false,
        Fepz2024:                            true,
        Odbiorkrotkitermin:                  true,
        Tylkonaszmagazyn:                    false,
        Kategoria:                           "Organizacja pozarządowa",
        Rodzajpomocy:                        "Żywność, odzież, wsparcie edukacyjne",
        Sposobudzielaniapomocy:              "Bezpośrednia dystrybucja",
        Warunkimagazynowe:                   "Suchy, ogrzewany magazyn",
        Haccp:                               true,
        Sanepid:                             true,
        Transportopis:                       "Dostępny transport własny",
        Transportkategoria:                  "Samochód dostawczy do 3,5t",
    }, nil
}
