environment="Development"

[charityUpdate]
operator_api_client_id = "03241880-d8b0-408f-800e-1a0aec3e8746"
operator_api_base_url = "http://localhost:5221"
mock_operator_api = false

[auth]
client_id = "3e93972c-5601-4a3f-946d-c46c4f93337e"
client_secret = ""
redirect_url = "http://localhost:8080/login/callback"
tenant_id = "454bf1c2-b7b2-4015-b836-a35ce5eed838"
hash_key = ""
block_key = ""

[logger]
level = "debug"
