// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.924
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Login() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div style=\"width: 50%;\"><form action=\"/login\" method=\"POST\" hx-target=\"#ErrorContainer\" hx-indicator=\"#spinner\"><input type=\"submit\" name=\"Login\" value=\"Zaloguj\"><div id=\"ErrorContainer\"></div><div id=\"spinner\" class=\"htmx-indicator\" style=\"text-align:center; height:50px;\"><svg style=\"fill: var(--pico-primary-background)\" viewBox=\"0 0 24 24\" xmlns=\"http://www.w3.org/2000/svg\"><style>\n\t\t\t\t\t.spinner_mHwL {\n\t\t\t\t\t\tanimation: spinner_OeFQ .75s cubic-bezier(0.56, .52, .17, .98) infinite\n\t\t\t\t\t}\n\n\t\t\t\t\t.spinner_ote2 {\n\t\t\t\t\t\tanimation: spinner_ZEPt .75s cubic-bezier(0.56, .52, .17, .98) infinite\n\t\t\t\t\t}\n\n\t\t\t\t\t@keyframes spinner_OeFQ {\n\t\t\t\t\t\t0% {\n\t\t\t\t\t\t\tcx: 4px;\n\t\t\t\t\t\t\tr: 3px\n\t\t\t\t\t\t}\n\n\t\t\t\t\t\t50% {\n\t\t\t\t\t\t\tcx: 9px;\n\t\t\t\t\t\t\tr: 8px\n\t\t\t\t\t\t}\n\t\t\t\t\t}\n\n\t\t\t\t\t@keyframes spinner_ZEPt {\n\t\t\t\t\t\t0% {\n\t\t\t\t\t\t\tcx: 15px;\n\t\t\t\t\t\t\tr: 8px\n\t\t\t\t\t\t}\n\n\t\t\t\t\t\t50% {\n\t\t\t\t\t\t\tcx: 20px;\n\t\t\t\t\t\t\tr: 3px\n\t\t\t\t\t\t}\n\t\t\t\t\t}\n\t\t\t\t</style><defs><filter id=\"spinner-gF00\"><feGaussianBlur in=\"SourceGraphic\" stdDeviation=\"1.5\" result=\"y\"></feGaussianBlur> <feColorMatrix in=\"y\" mode=\"matrix\" values=\"1 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 18 -7\" result=\"z\"></feColorMatrix> <feBlend in=\"SourceGraphic\" in2=\"z\"></feBlend></filter></defs> <g filter=\"url(#spinner-gF00)\"><circle class=\"spinner_mHwL\" cx=\"4\" cy=\"12\" r=\"3\"></circle> <circle class=\"spinner_ote2\" cx=\"15\" cy=\"12\" r=\"8\"></circle></g></svg></div></form></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
